import type { Deck } from "./types";

// Psychological, Social, and Biological Foundations of Behavior.
export const psychDecks: Deck[] = [
  {
    name: "Learning & Memory",
    description: "Conditioning, memory stages, and forgetting.",
    cards: [
      ["Learning: classical conditioning", "What is classical conditioning?", "Learning by pairing a neutral stimulus with an unconditioned stimulus until it triggers a conditioned response (Pavlov)."],
      ["Learning: UCS vs CS", "In Pavlov's experiment, what are the UCS, UCR, CS, and CR?", "UCS: food. UCR: salivation to food. CS: bell. CR: salivation to the bell."],
      ["Learning: extinction", "What is extinction in classical conditioning?", "The conditioned response fades when the CS is repeatedly presented without the UCS."],
      ["Learning: operant conditioning", "What is operant conditioning?", "Behavior is shaped by its consequences (Skinner): reinforcement increases it, punishment decreases it."],
      ["Learning: reinforcement types", "What is the difference between positive and negative reinforcement?", "Positive adds a pleasant stimulus; negative removes an aversive one. Both increase behavior."],
      ["Learning: reinforcement schedules", "Which reinforcement schedule is the most resistant to extinction?", "Variable ratio (e.g. slot machines)."],
      ["Learning: observational", "What did Bandura's Bobo doll study show?", "Children learn aggression by observing and imitating models (observational learning)."],
      ["Memory: stages", "What are the three stages of the Atkinson-Shiffrin model?", "Sensory memory, short-term (working) memory, and long-term memory."],
      ["Memory: capacity", "What is the capacity of short-term memory?", "About 7 +/- 2 items, lasting about 20-30 seconds without rehearsal; chunking expands it."],
      ["Memory: explicit vs implicit", "What is the difference between explicit and implicit memory?", "Explicit (declarative): facts and events, consciously recalled. Implicit (procedural): skills and conditioned responses."],
      ["Memory: hippocampus", "Which brain structure forms new explicit memories?", "The hippocampus; damage causes anterograde amnesia."],
      ["Memory: serial position", "What is the serial position effect?", "People best recall the first (primacy) and last (recency) items in a list."],
      ["Memory: encoding", "What is the levels of processing model?", "Deeper (semantic) processing leads to better memory than shallow (structural or phonetic) processing."],
      ["Memory: interference", "What is the difference between proactive and retroactive interference?", "Proactive: old information interferes with new. Retroactive: new information interferes with old."],
      ["Memory: LTP", "What is long-term potentiation?", "A lasting increase in synaptic strength after repeated stimulation, thought to underlie learning and memory."],
    ],
  },
  {
    name: "Social Psychology",
    description: "Attitudes, attribution, conformity, and group behavior.",
    cards: [
      ["Social: fundamental attribution error", "What is the fundamental attribution error?", "Overemphasizing personality and underestimating situational factors when explaining others' behavior."],
      ["Social: self-serving bias", "What is the self-serving bias?", "Crediting success to oneself and blaming failures on external factors."],
      ["Social: cognitive dissonance", "What is cognitive dissonance?", "Discomfort from holding conflicting beliefs or behaviors, which leads people to change their attitudes (Festinger)."],
      ["Social: elaboration likelihood", "What are the two routes in the elaboration likelihood model?", "Central route (careful thought about arguments) and peripheral route (cues like attractiveness or credibility)."],
      ["Social: conformity", "What did Asch's line experiments show?", "People often conform to a group's incorrect answer because of social pressure."],
      ["Social: obedience", "What did Milgram's experiment show?", "Ordinary people obeyed an authority figure to deliver what they thought were harmful shocks."],
      ["Social: bystander effect", "What is the bystander effect?", "Individuals are less likely to help when others are present, due to diffusion of responsibility."],
      ["Social: social facilitation", "What is social facilitation?", "The presence of others improves performance on easy or well-learned tasks and impairs it on difficult ones."],
      ["Social: groupthink", "What is groupthink?", "A group's desire for harmony leads to poor decisions and suppression of dissent."],
      ["Social: group polarization", "What is group polarization?", "Group discussion strengthens the group's initial leaning toward a more extreme position."],
      ["Social: stanford prison", "What did the Stanford prison experiment suggest?", "Social roles and situations strongly shape behavior (though the study has been criticized methodologically)."],
      ["Social: stereotypes and prejudice", "What is the difference between stereotype, prejudice, and discrimination?", "Stereotype: a belief (cognitive). Prejudice: an attitude (affective). Discrimination: an action (behavioral)."],
      ["Social: in-group bias", "What is in-group bias?", "A tendency to favor members of one's own group over outsiders."],
      ["Social: contact hypothesis", "What does the contact hypothesis propose?", "Equal-status contact between groups under cooperative conditions reduces prejudice."],
      ["Social: Bem's self-perception theory", "What does self-perception theory propose?", "People infer their attitudes by observing their own behavior."],
    ],
  },
  {
    name: "Sociology: Stratification & Institutions",
    description: "Social structure, theoretical perspectives, and inequality.",
    cards: [
      ["Sociology: functionalism", "What does the functionalist perspective argue?", "Society is a system of interdependent parts that each serve a function to maintain stability (Durkheim, Parsons)."],
      ["Sociology: conflict theory", "What does conflict theory argue?", "Society is shaped by competition over scarce resources among groups with unequal power (Marx)."],
      ["Sociology: symbolic interactionism", "What does symbolic interactionism focus on?", "How individuals create meaning through everyday interactions and shared symbols (Mead, Blumer)."],
      ["Sociology: social constructionism", "What is social constructionism?", "Reality and categories (e.g. race, gender) are shaped by shared human interpretation, not fixed nature."],
      ["Sociology: social capital", "What is social capital?", "The resources and benefits gained from social networks and relationships."],
      ["Sociology: cultural capital", "What is cultural capital?", "Non-financial assets such as education, tastes, and style that promote social mobility (Bourdieu)."],
      ["Sociology: social mobility", "What is the difference between intergenerational and intragenerational mobility?", "Intergenerational: change across generations. Intragenerational: change within one person's lifetime."],
      ["Sociology: class and status", "How did Weber define social stratification?", "By class (wealth), status (prestige), and power."],
      ["Sociology: anomie", "What is anomie?", "A breakdown of social norms and bonds, leading to normlessness (Durkheim)."],
      ["Sociology: deviance", "What does labeling theory say about deviance?", "Deviance results from society labeling certain behaviors, and the label shapes the person's identity."],
      ["Sociology: Gemeinschaft vs Gesellschaft", "What is the difference between Gemeinschaft and Gesellschaft?", "Gemeinschaft: community with close personal ties. Gesellschaft: society with impersonal, contractual ties."],
      ["Sociology: demographic transition", "What are the stages of the demographic transition?", "High birth and death rates; falling death rate (growth); falling birth rate; low birth and death rates."],
      ["Sociology: segregation", "What is the difference between segregation, assimilation, and multiculturalism?", "Segregation: physical separation. Assimilation: adoption of the dominant culture. Multiculturalism: coexistence of distinct cultures."],
      ["Sociology: health disparities", "What is the social gradient in health?", "Health outcomes improve with each step up in socioeconomic status."],
      ["Sociology: dramaturgical approach", "What is Goffman's dramaturgical approach?", "Social life is a performance: people manage impressions on a 'front stage' and relax on a 'back stage'."],
    ],
  },
];
