import type { Deck } from "./types";

// Biological and Biochemical Foundations of Living Systems. Each card is [label, prompt, answer].
export const bioDecks: Deck[] = [
  {
    name: "Amino Acids & Proteins",
    description: "Amino acid properties, peptide bonds, and protein structure levels.",
    cards: [
      ["Amino acids: general structure", "What four groups attach to the alpha carbon of an amino acid?", "An amino group, a carboxyl group, a hydrogen, and a variable R group."],
      ["Amino acids: chirality", "Which stereochemical configuration do the amino acids in human proteins have?", "L (and almost all are S, except cysteine, which is R)."],
      ["Amino acids: nonpolar", "Name four nonpolar, hydrophobic amino acids.", "Examples: alanine, valine, leucine, isoleucine, phenylalanine, methionine, tryptophan, proline, glycine."],
      ["Amino acids: acidic", "Which two amino acids have acidic side chains, and what is their charge at physiological pH?", "Aspartate and glutamate; both are negatively charged at pH 7.4."],
      ["Amino acids: basic", "Which three amino acids have basic side chains?", "Lysine, arginine, and histidine."],
      ["Amino acids: isoelectric point", "What is the isoelectric point (pI) of an amino acid?", "The pH at which it has no net charge (exists as a zwitterion)."],
      ["Amino acids: cysteine", "What bond can two cysteine residues form, and what does it do?", "A disulfide bond (covalent), which stabilizes tertiary and quaternary structure."],
      ["Proteins: peptide bond", "What type of reaction forms a peptide bond, and what is released?", "A dehydration (condensation) reaction; water is released."],
      ["Proteins: peptide direction", "In which direction are polypeptides written and synthesized?", "N-terminus to C-terminus."],
      ["Proteins: primary structure", "What is a protein's primary structure?", "The linear sequence of amino acids, held together by peptide bonds."],
      ["Proteins: secondary structure", "What stabilizes alpha helices and beta sheets?", "Hydrogen bonds between backbone carbonyl oxygens and amide hydrogens."],
      ["Proteins: tertiary structure", "Which interactions stabilize tertiary structure?", "Hydrophobic interactions, hydrogen bonds, ionic bonds, and disulfide bridges between R groups."],
      ["Proteins: quaternary structure", "What is quaternary structure?", "The arrangement of multiple polypeptide subunits in one functional protein, e.g. hemoglobin."],
      ["Proteins: denaturation", "Name two things that can denature a protein, and what is lost.", "Heat, extreme pH, urea, or detergents; secondary through quaternary structure is lost, but primary structure remains."],
      ["Proteins: proline", "Why does proline disrupt alpha helices?", "Its rigid ring and lack of a backbone amide hydrogen introduce kinks and prevent hydrogen bonding."],
    ],
  },
  {
    name: "Enzyme Kinetics",
    description: "Michaelis-Menten kinetics, inhibition types, and enzyme regulation.",
    cards: [
      ["Enzymes: catalysis", "How do enzymes speed up reactions?", "By lowering the activation energy; they do not change the equilibrium or delta G."],
      ["Enzymes: induced fit", "What does the induced fit model say?", "Substrate binding causes a conformational change in the enzyme's active site that improves the fit."],
      ["Kinetics: Vmax", "What does Vmax represent?", "The maximum reaction rate when all enzyme active sites are saturated with substrate."],
      ["Kinetics: Km", "What is Km?", "The substrate concentration at which the rate is half of Vmax; a lower Km means higher affinity."],
      ["Kinetics: Michaelis-Menten", "What is the Michaelis-Menten equation?", "v = Vmax[S] / (Km + [S])"],
      ["Kinetics: Lineweaver-Burk", "What do the axes and intercepts of a Lineweaver-Burk plot show?", "1/v vs 1/[S]; y-intercept is 1/Vmax, x-intercept is -1/Km."],
      ["Kinetics: kcat", "What is kcat?", "The turnover number: substrate molecules converted per enzyme per second at saturation."],
      ["Inhibition: competitive", "How does a competitive inhibitor change Km and Vmax?", "Km increases, Vmax is unchanged (overcome by more substrate)."],
      ["Inhibition: noncompetitive", "How does a noncompetitive inhibitor change Km and Vmax?", "Vmax decreases, Km is unchanged."],
      ["Inhibition: uncompetitive", "How does an uncompetitive inhibitor change Km and Vmax?", "Both decrease; it binds only the enzyme-substrate complex."],
      ["Inhibition: mixed", "How does a mixed inhibitor behave?", "It binds both E and ES with different affinities; Vmax decreases and Km can go up or down."],
      ["Regulation: allosteric", "What is allosteric regulation?", "Binding of an effector at a site other than the active site changes enzyme activity."],
      ["Regulation: cooperativity", "What kind of curve do cooperative enzymes show?", "A sigmoidal curve, rather than the hyperbolic Michaelis-Menten curve."],
      ["Regulation: covalent modification", "Give an example of covalent enzyme regulation.", "Phosphorylation by kinases and dephosphorylation by phosphatases; also zymogen cleavage."],
      ["Enzymes: cofactors", "What is the difference between a cofactor and a coenzyme?", "Cofactors are inorganic ions (e.g. Mg2+, Zn2+); coenzymes are organic molecules (e.g. NAD+, many vitamin derivatives)."],
    ],
  },
  {
    name: "Glycolysis & Fermentation",
    description: "Glucose catabolism, key regulatory enzymes, and anaerobic pathways.",
    cards: [
      ["Glycolysis: location", "Where does glycolysis occur?", "In the cytoplasm."],
      ["Glycolysis: net yield", "What is the net yield of glycolysis per glucose?", "2 pyruvate, 2 ATP, and 2 NADH."],
      ["Glycolysis: ATP investment", "How many ATP are invested and how many are produced per glucose?", "2 invested, 4 produced, for a net of 2."],
      ["Glycolysis: rate-limiting step", "Which enzyme is the main rate-limiting step of glycolysis?", "Phosphofructokinase-1 (PFK-1), converting fructose-6-phosphate to fructose-1,6-bisphosphate."],
      ["Glycolysis: PFK-1 regulation", "What activates and inhibits PFK-1?", "Activated by AMP and fructose-2,6-bisphosphate; inhibited by ATP and citrate."],
      ["Glycolysis: hexokinase", "What does hexokinase do, and how is it inhibited?", "Phosphorylates glucose to glucose-6-phosphate (trapping it in the cell); inhibited by its product, G6P."],
      ["Glycolysis: glucokinase", "How does glucokinase differ from hexokinase?", "It is found in liver and pancreatic beta cells, has a higher Km and a higher Vmax, and is not inhibited by G6P."],
      ["Glycolysis: substrate-level phosphorylation", "What is substrate-level phosphorylation?", "Direct transfer of a phosphate from a substrate to ADP to make ATP, e.g. phosphoenolpyruvate to pyruvate."],
      ["Glycolysis: pyruvate kinase", "What is the last step of glycolysis, and what activates it?", "PEP to pyruvate by pyruvate kinase; activated by fructose-1,6-bisphosphate (feed-forward)."],
      ["Fermentation: purpose", "Why do cells ferment pyruvate under anaerobic conditions?", "To regenerate NAD+ so glycolysis can continue."],
      ["Fermentation: lactic acid", "What does lactic acid fermentation produce?", "Lactate from pyruvate, using NADH, via lactate dehydrogenase."],
      ["Fermentation: alcohol", "What does alcohol fermentation in yeast produce?", "Ethanol and CO2 from pyruvate."],
      ["Gluconeogenesis: irreversible steps", "Which glycolytic steps must be bypassed in gluconeogenesis?", "The three irreversible ones: hexokinase, PFK-1, and pyruvate kinase."],
      ["Pentose phosphate pathway", "What does the pentose phosphate pathway produce?", "NADPH (for biosynthesis and defense against oxidative stress) and ribose-5-phosphate."],
      ["Glycolysis: Warburg effect", "What is the Warburg effect?", "Many cancer cells rely on glycolysis and lactate production even when oxygen is available."],
    ],
  },
  {
    name: "Citric Acid Cycle & Oxidative Phosphorylation",
    description: "Pyruvate oxidation, the TCA cycle, the electron transport chain, and ATP synthase.",
    cards: [
      ["PDH: pyruvate dehydrogenase", "What does the pyruvate dehydrogenase complex produce from pyruvate?", "Acetyl-CoA, CO2, and NADH; it takes place in the mitochondrial matrix."],
      ["TCA: location", "Where does the citric acid cycle occur in eukaryotes?", "In the mitochondrial matrix."],
      ["TCA: first step", "What two molecules combine in the first step of the TCA cycle?", "Acetyl-CoA and oxaloacetate form citrate, via citrate synthase."],
      ["TCA: yield per acetyl-CoA", "What does one turn of the TCA cycle produce?", "3 NADH, 1 FADH2, 1 GTP (or ATP), and 2 CO2."],
      ["TCA: yield per glucose", "How many turns of the TCA cycle occur per glucose?", "Two, one for each acetyl-CoA."],
      ["TCA: regulation", "Which enzymes are the major regulation points of the TCA cycle?", "Citrate synthase, isocitrate dehydrogenase, and alpha-ketoglutarate dehydrogenase; inhibited by ATP and NADH."],
      ["ETC: location", "Where is the electron transport chain located?", "In the inner mitochondrial membrane."],
      ["ETC: electron carriers", "What donates electrons to the ETC, and where do they enter?", "NADH enters at Complex I; FADH2 enters at Complex II (via succinate dehydrogenase)."],
      ["ETC: final acceptor", "What is the final electron acceptor and the product?", "Oxygen, reduced to water at Complex IV."],
      ["ETC: proton gradient", "What does the ETC do with the energy from electron transfer?", "Pumps protons from the matrix into the intermembrane space, creating a proton-motive force."],
      ["ETC: Complex II", "Which ETC complex does not pump protons?", "Complex II (succinate dehydrogenase)."],
      ["ATP synthase: mechanism", "How does ATP synthase make ATP?", "Protons flow down their gradient through the F0 subunit, driving rotation of F1 that phosphorylates ADP."],
      ["Oxidative phosphorylation: P/O ratio", "Approximately how many ATP are made per NADH and per FADH2?", "About 2.5 per NADH and 1.5 per FADH2."],
      ["Oxidative phosphorylation: uncouplers", "What does an uncoupler like DNP do?", "Dissipates the proton gradient, so oxygen is consumed and heat is produced, but little ATP is made."],
      ["Mitochondria: shuttles", "Why are shuttles like glycerol-3-phosphate and malate-aspartate needed?", "NADH made in the cytoplasm can't cross the inner mitochondrial membrane, so shuttles move its electrons in."],
    ],
  },
  {
    name: "DNA Replication & Repair",
    description: "Replication machinery, fidelity, and repair mechanisms.",
    cards: [
      ["Replication: semiconservative", "What does semiconservative replication mean?", "Each new DNA molecule has one original strand and one newly synthesized strand."],
      ["Replication: origin", "What is the origin of replication?", "A specific sequence where unwinding starts; bacteria have one, eukaryotes have many."],
      ["Replication: helicase", "What does helicase do?", "Unwinds the double helix by breaking hydrogen bonds between base pairs, using ATP."],
      ["Replication: SSB proteins", "What do single-strand binding proteins do?", "Keep separated strands apart so they don't re-anneal or form secondary structures."],
      ["Replication: topoisomerase", "What is the role of topoisomerase (gyrase)?", "Relieves supercoiling ahead of the replication fork by cutting and rejoining strands."],
      ["Replication: primase", "Why is primase needed?", "DNA polymerase can't start a chain; primase makes a short RNA primer to give it a 3' OH."],
      ["Replication: direction", "In which direction does DNA polymerase synthesize, and what does it read?", "It synthesizes 5' to 3' and reads the template 3' to 5'."],
      ["Replication: leading strand", "What is the leading strand?", "The strand synthesized continuously toward the replication fork."],
      ["Replication: lagging strand", "What are Okazaki fragments?", "Short DNA segments made discontinuously on the lagging strand, away from the fork."],
      ["Replication: DNA polymerase III", "What is the main replicating enzyme in prokaryotes?", "DNA polymerase III; it also has 3' to 5' exonuclease proofreading activity."],
      ["Replication: DNA polymerase I", "What does DNA polymerase I do?", "Removes RNA primers (5' to 3' exonuclease) and fills the gaps with DNA."],
      ["Replication: ligase", "What does DNA ligase do?", "Seals nicks by forming a phosphodiester bond between adjacent fragments."],
      ["Replication: telomeres", "What does telomerase do?", "Extends telomeres using its own RNA template, solving the end-replication problem."],
      ["Repair: mismatch repair", "How does mismatch repair work?", "Recognizes mismatched bases after replication, removes the new strand segment, and resynthesizes it."],
      ["Repair: nucleotide excision", "What does nucleotide excision repair fix?", "Bulky lesions such as UV-induced thymine dimers; a defect causes xeroderma pigmentosum."],
    ],
  },
  {
    name: "Transcription & Translation",
    description: "Gene expression from DNA to RNA to protein.",
    cards: [
      ["Transcription: RNA polymerase", "What does RNA polymerase need to begin transcription in eukaryotes?", "A promoter (e.g. the TATA box) and transcription factors; no primer is needed."],
      ["Transcription: direction", "In which direction is mRNA synthesized, and which strand is read?", "5' to 3'; the template (antisense) strand is read 3' to 5'."],
      ["Transcription: eukaryotic polymerases", "What does RNA polymerase II transcribe?", "mRNA (pol I makes most rRNA, pol III makes tRNA)."],
      ["mRNA processing: 5' cap", "What is added to the 5' end of eukaryotic mRNA, and why?", "A 7-methylguanosine cap, for ribosome binding and protection from degradation."],
      ["mRNA processing: poly-A tail", "What does the poly-A tail do?", "Protects the mRNA from degradation and aids in export and translation."],
      ["mRNA processing: splicing", "What does the spliceosome do?", "Removes introns and joins exons; it is made of snRNPs."],
      ["mRNA processing: alternative splicing", "What is alternative splicing?", "Different exon combinations from one gene give different mRNAs and protein isoforms."],
      ["Gene regulation: operons", "What is the lac operon controlled by?", "The lac repressor (blocked by allolactose) and CAP-cAMP (active when glucose is low)."],
      ["Genetic code: properties", "What does it mean that the genetic code is degenerate?", "Multiple codons code for the same amino acid."],
      ["Genetic code: start and stop", "What are the start and stop codons?", "Start: AUG (methionine). Stop: UAA, UAG, UGA."],
      ["Translation: tRNA", "What does aminoacyl-tRNA synthetase do?", "Attaches the correct amino acid to its tRNA; it is the step that ensures translational accuracy."],
      ["Translation: ribosome sites", "What are the three tRNA binding sites of the ribosome?", "A (aminoacyl), P (peptidyl), and E (exit)."],
      ["Translation: ribosome subunits", "What are the eukaryotic ribosomal subunits?", "40S small and 60S large, together an 80S ribosome."],
      ["Translation: initiation", "What happens during initiation?", "The small subunit binds the mRNA cap, finds AUG, and the initiator tRNA and large subunit join."],
      ["Mutations: types", "What is the difference between missense, nonsense, and frameshift mutations?", "Missense changes one amino acid; nonsense creates a premature stop codon; frameshift (indel not divisible by 3) alters the downstream reading frame."],
    ],
  },
  {
    name: "Mendelian Genetics",
    description: "Inheritance patterns, probability, and population genetics.",
    cards: [
      ["Mendel: law of segregation", "What is Mendel's law of segregation?", "Each organism carries two alleles for a trait, which separate during gamete formation so each gamete gets one."],
      ["Mendel: independent assortment", "What is the law of independent assortment?", "Alleles of different genes assort independently, as long as the genes are on different chromosomes or far apart."],
      ["Genetics: genotype vs phenotype", "What is the difference between genotype and phenotype?", "Genotype is the allele combination; phenotype is the observable trait."],
      ["Genetics: monohybrid cross", "What phenotype ratio comes from crossing two heterozygotes (Aa x Aa)?", "3:1 dominant to recessive (genotypes 1:2:1)."],
      ["Genetics: dihybrid cross", "What phenotype ratio comes from AaBb x AaBb?", "9:3:3:1."],
      ["Genetics: test cross", "What is a test cross?", "Crossing an unknown dominant phenotype with a homozygous recessive to determine its genotype."],
      ["Genetics: incomplete dominance", "What is incomplete dominance?", "The heterozygote has an intermediate phenotype, e.g. red x white gives pink."],
      ["Genetics: codominance", "What is codominance?", "Both alleles are fully expressed in the heterozygote, e.g. AB blood type."],
      ["Genetics: sex-linked", "Why are X-linked recessive disorders more common in males?", "Males are hemizygous (one X), so one recessive allele gives the phenotype."],
      ["Genetics: carrier fathers", "Can an X-linked recessive trait be passed from father to son?", "No; fathers pass their Y to sons and their X only to daughters."],
      ["Genetics: linkage", "How does genetic distance relate to recombination frequency?", "1% recombination frequency = 1 map unit (centimorgan); closer genes recombine less."],
      ["Genetics: Hardy-Weinberg equations", "What are the Hardy-Weinberg equations?", "p + q = 1 and p^2 + 2pq + q^2 = 1."],
      ["Genetics: Hardy-Weinberg conditions", "What conditions are needed for Hardy-Weinberg equilibrium?", "Large population, random mating, no mutation, no migration, no selection."],
      ["Genetics: epistasis", "What is epistasis?", "One gene's alleles mask or modify the expression of another gene."],
      ["Genetics: penetrance", "What is the difference between penetrance and expressivity?", "Penetrance is the proportion with the genotype who show any phenotype; expressivity is the degree to which the phenotype is shown."],
    ],
  },
  {
    name: "Cardiovascular & Respiratory Physiology",
    description: "Blood flow, the heart, gas exchange, and hemoglobin.",
    cards: [
      ["Heart: blood flow path", "What is the path of blood through the heart?", "Vena cava, right atrium, right ventricle, pulmonary artery, lungs, pulmonary vein, left atrium, left ventricle, aorta."],
      ["Heart: valves", "What are the AV and semilunar valves?", "AV: tricuspid (right), bicuspid/mitral (left). Semilunar: pulmonary and aortic."],
      ["Heart: SA node", "What is the SA node?", "The pacemaker of the heart, which sets the rate of the sinus rhythm."],
      ["Heart: conduction", "What is the order of electrical conduction in the heart?", "SA node, AV node, bundle of His, Purkinje fibers."],
      ["Heart: cardiac output", "How is cardiac output calculated?", "CO = heart rate x stroke volume."],
      ["Vessels: arteries vs veins", "How do arteries and veins differ structurally?", "Arteries have thick, elastic, muscular walls for high pressure; veins have thin walls, larger lumens, and valves."],
      ["Vessels: capillaries", "What happens at capillary beds?", "Exchange of gases, nutrients, and wastes; Starling forces move fluid in and out."],
      ["Blood: oncotic pressure", "What does oncotic pressure do?", "Plasma proteins (mainly albumin) pull water into the capillary, opposing hydrostatic pressure."],
      ["Blood: hemoglobin", "How many O2 molecules can one hemoglobin carry?", "Four (one per heme group)."],
      ["Blood: oxygen dissociation curve", "Why is the oxygen-hemoglobin dissociation curve sigmoidal?", "Cooperative binding: each bound O2 increases the affinity for the next."],
      ["Blood: right shift", "What shifts the O2 dissociation curve to the right?", "Higher CO2, lower pH (Bohr effect), higher temperature, and more 2,3-BPG; hemoglobin releases O2 more readily."],
      ["Blood: CO2 transport", "How is most CO2 carried in the blood?", "As bicarbonate (HCO3-), formed via carbonic anhydrase in red blood cells."],
      ["Respiration: mechanics", "What happens when the diaphragm contracts?", "Thoracic volume increases, pressure drops, and air flows into the lungs (negative pressure breathing)."],
      ["Respiration: alveoli", "What does surfactant do?", "Reduces surface tension in the alveoli, preventing collapse."],
      ["Respiration: ventilation control", "What mainly drives the respiratory rate?", "Chemoreceptors sensing CO2/pH in the medulla; peripheral receptors sense low O2."],
    ],
  },
  {
    name: "Nervous System & Action Potentials",
    description: "Neuron structure, membrane potentials, and synaptic transmission.",
    cards: [
      ["Neuron: structure", "What are the main parts of a neuron, and what do they do?", "Dendrites receive signals, the soma integrates them, and the axon carries the signal away to the terminals."],
      ["Neuron: resting potential", "What is the resting membrane potential of a neuron and what sets it?", "About -70 mV, set by the Na+/K+ ATPase and K+ leak channels."],
      ["Neuron: Na+/K+ pump", "What does the Na+/K+ ATPase do per cycle?", "Pumps 3 Na+ out and 2 K+ in, using 1 ATP."],
      ["Action potential: depolarization", "What drives depolarization?", "Voltage-gated Na+ channels open, and Na+ rushes in."],
      ["Action potential: repolarization", "What drives repolarization?", "Na+ channels inactivate and voltage-gated K+ channels open, so K+ flows out."],
      ["Action potential: threshold", "What is the all-or-none principle?", "If the threshold (about -55 mV) is reached, a full action potential fires; otherwise nothing happens."],
      ["Action potential: refractory period", "What is the difference between absolute and relative refractory periods?", "Absolute: no new AP is possible (Na+ channels inactivated). Relative: a stronger stimulus is needed (hyperpolarized)."],
      ["Myelin: saltatory conduction", "How does myelination speed up conduction?", "The AP jumps between nodes of Ranvier (saltatory conduction); myelin increases membrane resistance."],
      ["Myelin: producers", "Which cells produce myelin?", "Oligodendrocytes in the CNS; Schwann cells in the PNS."],
      ["Synapse: neurotransmitter release", "What triggers neurotransmitter release?", "Voltage-gated Ca2+ channels open at the terminal, and Ca2+ causes vesicle fusion."],
      ["Synapse: acetylcholine", "What is acetylcholine's role, and what breaks it down?", "Neuromuscular junction, parasympathetic signaling; broken down by acetylcholinesterase."],
      ["Synapse: summation", "What is the difference between temporal and spatial summation?", "Temporal: rapid signals from one synapse add up. Spatial: signals from multiple synapses add up."],
      ["Nervous system: divisions", "What are the divisions of the autonomic nervous system?", "Sympathetic (fight or flight) and parasympathetic (rest and digest)."],
      ["Nervous system: reflex arc", "What is a reflex arc?", "A pathway through a sensory neuron, the spinal cord (and often an interneuron), and a motor neuron, without input from the brain."],
      ["Nervous system: GABA", "What is GABA?", "The main inhibitory neurotransmitter in the CNS; opens Cl- channels and hyperpolarizes the cell."],
    ],
  },
  {
    name: "Endocrine System",
    description: "Hormone classes, major glands, and feedback loops.",
    cards: [
      ["Hormones: peptide", "How do peptide hormones act?", "They bind cell-surface receptors and trigger second messenger cascades (e.g. cAMP); they act quickly."],
      ["Hormones: steroid", "How do steroid hormones act?", "They cross the membrane, bind intracellular receptors, and alter gene transcription; slower but longer-lasting."],
      ["Hormones: G protein pathways", "What does the Gs pathway do?", "Activates adenylyl cyclase, increases cAMP, and activates protein kinase A."],
      ["Hypothalamus: pituitary link", "How does the hypothalamus control the anterior pituitary?", "It releases hormones (e.g. TRH, GnRH, CRH) into the portal system."],
      ["Posterior pituitary", "Which hormones does the posterior pituitary release?", "ADH (vasopressin) and oxytocin, both made in the hypothalamus."],
      ["Anterior pituitary", "Name the anterior pituitary hormones.", "FSH, LH, ACTH, TSH, GH, and prolactin."],
      ["Thyroid: hormones", "What do T3 and T4 do?", "Increase basal metabolic rate; iodine is needed to make them."],
      ["Thyroid: calcitonin", "What does calcitonin do?", "Lowers blood calcium by promoting bone deposition."],
      ["Parathyroid: PTH", "What does PTH do?", "Raises blood calcium: bone resorption, kidney reabsorption, and activation of vitamin D."],
      ["Pancreas: insulin", "What does insulin do?", "Lowers blood glucose: promotes glucose uptake, glycogen synthesis, and fat storage."],
      ["Pancreas: glucagon", "What does glucagon do?", "Raises blood glucose: promotes glycogenolysis and gluconeogenesis in the liver."],
      ["Adrenal: cortex", "What does the adrenal cortex produce?", "Cortisol (stress, glucocorticoid), aldosterone (Na+ retention), and androgens."],
      ["Adrenal: medulla", "What does the adrenal medulla release?", "Epinephrine and norepinephrine, under sympathetic control."],
      ["Feedback: negative", "What is negative feedback?", "The output of a pathway inhibits its own production, e.g. cortisol inhibiting CRH and ACTH."],
      ["Feedback: positive", "Give an example of positive feedback in endocrinology.", "Oxytocin during labor, or the LH surge before ovulation."],
    ],
  },
];
