import type { Deck } from "./types";

// Chemical and Physical Foundations (general chemistry, physics) plus organic chemistry.
export const chemDecks: Deck[] = [
  {
    name: "Acids & Bases",
    description: "pH, Ka and pKa, buffers, and titrations.",
    cards: [
      ["Acids: Bronsted-Lowry", "What is the Bronsted-Lowry definition of an acid and a base?", "An acid donates a proton (H+); a base accepts a proton."],
      ["Acids: Lewis", "What is the Lewis definition of an acid and a base?", "A Lewis acid accepts an electron pair; a Lewis base donates an electron pair."],
      ["Acids: pH", "How is pH defined?", "pH = -log[H+]; pH 7 is neutral at 25 C."],
      ["Acids: Kw", "What is Kw at 25 C and how does it relate pH and pOH?", "Kw = [H+][OH-] = 1 x 10^-14; pH + pOH = 14."],
      ["Acids: strong acids", "Name the six common strong acids.", "HCl, HBr, HI, HNO3, H2SO4, HClO4."],
      ["Acids: Ka and pKa", "How do Ka and pKa relate to acid strength?", "A larger Ka (smaller pKa) means a stronger acid; pKa = -log Ka."],
      ["Acids: conjugate pairs", "What is the relationship between Ka of an acid and Kb of its conjugate base?", "Ka x Kb = Kw."],
      ["Acids: acid strength trends", "Why is HI a stronger acid than HF?", "The H-I bond is longer and weaker, so it dissociates more easily, despite fluorine's higher electronegativity."],
      ["Buffers: composition", "What is a buffer made of?", "A weak acid and its conjugate base (or a weak base and its conjugate acid) in comparable amounts."],
      ["Buffers: Henderson-Hasselbalch", "What is the Henderson-Hasselbalch equation?", "pH = pKa + log([A-]/[HA])"],
      ["Buffers: best range", "At what pH is a buffer most effective?", "Within about 1 pH unit of the pKa; at pH = pKa, [A-] = [HA]."],
      ["Titration: equivalence point", "What is the pH at the equivalence point for a strong acid-strong base titration?", "7; for a weak acid titrated with a strong base it is above 7."],
      ["Titration: half-equivalence", "What is true at the half-equivalence point of a weak acid titration?", "pH = pKa, because [HA] = [A-]."],
      ["Acids: amphoteric", "What is an amphoteric species?", "One that can act as both an acid and a base, e.g. water, HCO3-, amino acids."],
      ["Acids: polyprotic", "Why is Ka2 smaller than Ka1 for a polyprotic acid?", "It is harder to remove a proton from an already negatively charged species."],
    ],
  },
  {
    name: "Thermochemistry & Thermodynamics",
    description: "Enthalpy, entropy, Gibbs free energy, and equilibrium.",
    cards: [
      ["Thermo: first law", "What does the first law of thermodynamics say?", "Energy is conserved: delta U = q - w (heat added minus work done by the system)."],
      ["Thermo: enthalpy", "What does a negative delta H mean?", "The reaction is exothermic: it releases heat to the surroundings."],
      ["Thermo: second law", "What does the second law of thermodynamics say?", "The entropy of the universe increases in any spontaneous process."],
      ["Thermo: entropy", "What generally increases entropy?", "More gas molecules, more particles, higher temperature, and the change from solid to liquid to gas."],
      ["Thermo: Gibbs free energy", "What is the equation for Gibbs free energy?", "delta G = delta H - T delta S"],
      ["Thermo: spontaneity", "What does the sign of delta G tell you?", "Negative: spontaneous (exergonic). Positive: nonspontaneous. Zero: at equilibrium."],
      ["Thermo: sign combinations", "When is a reaction spontaneous at all temperatures?", "When delta H < 0 and delta S > 0."],
      ["Thermo: delta G and K", "How do delta G degrees and K relate?", "delta G degrees = -RT ln K; K > 1 means delta G degrees < 0."],
      ["Thermo: reaction quotient", "How does delta G relate to Q?", "delta G = delta G degrees + RT ln Q"],
      ["Thermo: Hess's law", "What is Hess's law?", "The total enthalpy change is the sum of the changes of the steps, regardless of path."],
      ["Thermo: bond enthalpy", "How can you estimate delta H from bond enthalpies?", "delta H = bonds broken (energy in) minus bonds formed (energy out)."],
      ["Thermo: calorimetry", "What is the calorimetry equation?", "q = mc delta T"],
      ["Equilibrium: Le Chatelier", "What does Le Chatelier's principle say?", "A system at equilibrium shifts to partially counteract any applied stress."],
      ["Equilibrium: temperature", "How does raising temperature affect an exothermic reaction at equilibrium?", "It shifts toward reactants (K decreases)."],
      ["Equilibrium: catalysts", "What does a catalyst do to K and to the rate?", "No change in K; it increases the rate by lowering the activation energy for both directions."],
    ],
  },
  {
    name: "Electrochemistry",
    description: "Galvanic and electrolytic cells, cell potentials, and the Nernst equation.",
    cards: [
      ["Electrochem: oxidation and reduction", "What is oxidation and reduction?", "Oxidation is loss of electrons; reduction is gain of electrons (OIL RIG)."],
      ["Electrochem: electrodes", "What occurs at the anode and the cathode?", "Oxidation at the anode; reduction at the cathode (always)."],
      ["Electrochem: galvanic cell", "What is a galvanic cell?", "A spontaneous reaction produces electricity; E cell > 0, delta G < 0."],
      ["Electrochem: electrolytic cell", "What is an electrolytic cell?", "An external power source drives a nonspontaneous reaction; E cell < 0, delta G > 0."],
      ["Electrochem: electrode signs", "What are the electrode charges in galvanic vs electrolytic cells?", "Galvanic: anode (-), cathode (+). Electrolytic: anode (+), cathode (-)."],
      ["Electrochem: salt bridge", "What does the salt bridge do?", "Maintains charge neutrality by letting ions flow between half-cells."],
      ["Electrochem: electron flow", "Which way do electrons flow in a cell?", "From the anode to the cathode through the external wire."],
      ["Electrochem: cell potential", "How do you calculate the standard cell potential?", "E degrees cell = E degrees reduction (cathode) - E degrees reduction (anode)."],
      ["Electrochem: delta G", "How is delta G related to cell potential?", "delta G degrees = -nF E degrees"],
      ["Electrochem: Nernst", "What is the Nernst equation?", "E = E degrees - (RT/nF) ln Q, or at 25 C: E = E degrees - (0.0592/n) log Q."],
      ["Electrochem: concentration cells", "What is true of a concentration cell?", "E degrees = 0; the potential comes from a concentration difference, and electrons flow toward equalizing it."],
      ["Electrochem: Faraday's constant", "What is Faraday's constant?", "About 96,485 C per mole of electrons."],
      ["Electrochem: electrolysis", "How do you find the moles of metal deposited in electrolysis?", "moles = (I x t) / (n x F)"],
      ["Electrochem: reducing agents", "What is the strongest reducing agent?", "The species with the most negative reduction potential; it is oxidized most readily."],
      ["Electrochem: batteries", "What happens to E cell as a battery discharges?", "Q increases toward K, so E falls toward 0 at equilibrium (a dead battery)."],
    ],
  },
  {
    name: "Gases & Solutions",
    description: "Ideal gas law, kinetic molecular theory, colligative properties, and solubility.",
    cards: [
      ["Gases: ideal gas law", "What is the ideal gas law?", "PV = nRT"],
      ["Gases: STP molar volume", "What is the volume of one mole of ideal gas at STP?", "22.4 L (at 0 C and 1 atm)."],
      ["Gases: Boyle's law", "What does Boyle's law say?", "At constant T and n, pressure and volume are inversely related: P1V1 = P2V2."],
      ["Gases: Charles's law", "What does Charles's law say?", "At constant P and n, volume is proportional to absolute temperature (in kelvin)."],
      ["Gases: Avogadro", "What does Avogadro's law say?", "At constant T and P, volume is proportional to moles of gas."],
      ["Gases: Dalton", "What is Dalton's law of partial pressures?", "P total is the sum of partial pressures; P of A = mole fraction of A x P total."],
      ["Gases: kinetic theory", "What does temperature measure in kinetic molecular theory?", "The average kinetic energy of the particles: KE = (3/2)kT."],
      ["Gases: Graham's law", "What does Graham's law say?", "Rate of effusion is inversely proportional to the square root of molar mass."],
      ["Gases: real gases", "When do real gases deviate most from ideal behavior?", "At high pressure and low temperature, where particle volume and attraction matter."],
      ["Solutions: molarity vs molality", "What is the difference between molarity and molality?", "Molarity = mol solute / L solution; molality = mol solute / kg solvent (independent of temperature)."],
      ["Solutions: colligative properties", "What are the four colligative properties?", "Vapor pressure lowering, boiling point elevation, freezing point depression, and osmotic pressure."],
      ["Solutions: van't Hoff factor", "What is the van't Hoff factor (i)?", "The number of particles a solute dissociates into, e.g. i = 3 for CaCl2."],
      ["Solutions: Raoult's law", "What is Raoult's law?", "The vapor pressure of a solvent equals its mole fraction times the pure solvent vapor pressure."],
      ["Solutions: osmotic pressure", "How do you calculate osmotic pressure?", "Pi = iMRT"],
      ["Solutions: Ksp", "What does Ksp represent, and what is the common ion effect?", "Ksp is the solubility product of a sparingly soluble salt; adding a common ion lowers its solubility."],
    ],
  },
  {
    name: "Kinematics & Newton's Laws",
    description: "Motion in one and two dimensions, forces, work, and energy.",
    cards: [
      ["Kinematics: scalar vs vector", "What is the difference between speed and velocity, distance and displacement?", "Speed and distance are scalars; velocity and displacement are vectors with direction."],
      ["Kinematics: equations", "What are the five kinematic equations for constant acceleration?", "v = v0 + at; x = v0t + (1/2)at^2; v^2 = v0^2 + 2ax; x = (v0 + v)t/2; x = vt - (1/2)at^2."],
      ["Kinematics: free fall", "What is the acceleration of an object in free fall near Earth, ignoring air resistance?", "g = 9.8 m/s^2 downward (about 10 m/s^2 for MCAT estimates), independent of mass."],
      ["Kinematics: projectile", "How do you treat projectile motion?", "Separately: horizontal velocity is constant, and vertical motion has constant acceleration g."],
      ["Kinematics: max height", "What is the vertical velocity at the top of a projectile's path?", "Zero; the acceleration is still g, downward."],
      ["Newton: first law", "What is Newton's first law?", "An object stays at rest or in constant velocity unless acted on by a net force (inertia)."],
      ["Newton: second law", "What is Newton's second law?", "F net = ma"],
      ["Newton: third law", "What is Newton's third law?", "Forces come in equal and opposite pairs acting on different objects."],
      ["Forces: friction", "What are the equations for static and kinetic friction?", "Static: f <= mu_s N. Kinetic: f = mu_k N; mu_s is usually larger than mu_k."],
      ["Forces: inclined plane", "On an incline of angle theta, what is the force along the surface and the normal force?", "Along: mg sin(theta). Normal: N = mg cos(theta)."],
      ["Forces: centripetal", "What is the centripetal acceleration?", "a = v^2/r, directed toward the center of the circle."],
      ["Energy: work", "How is work defined?", "W = Fd cos(theta); the unit is the joule."],
      ["Energy: work-energy theorem", "What is the work-energy theorem?", "The net work done on an object equals its change in kinetic energy: W = delta KE."],
      ["Energy: conservation", "When is mechanical energy conserved?", "When only conservative forces (e.g. gravity, springs) do work; KE + PE stays constant."],
      ["Energy: power", "What is power?", "P = W/t = Fv; the unit is the watt."],
    ],
  },
  {
    name: "Circuits",
    description: "Ohm's law, resistors, capacitors, and power in DC circuits.",
    cards: [
      ["Circuits: Ohm's law", "What is Ohm's law?", "V = IR"],
      ["Circuits: current", "What is the definition of current?", "The rate of charge flow: I = delta Q / delta t, measured in amperes."],
      ["Circuits: resistors in series", "How do you find the equivalent resistance of resistors in series?", "R eq = R1 + R2 + ... ; the same current flows through each."],
      ["Circuits: resistors in parallel", "How do you find the equivalent resistance of resistors in parallel?", "1/R eq = 1/R1 + 1/R2 + ... ; the same voltage across each, and R eq is smaller than any one."],
      ["Circuits: power", "What are the equations for electrical power?", "P = IV = I^2 R = V^2/R"],
      ["Circuits: Kirchhoff's junction rule", "What is Kirchhoff's junction rule?", "Current into a junction equals current out (conservation of charge)."],
      ["Circuits: Kirchhoff's loop rule", "What is Kirchhoff's loop rule?", "The sum of voltage changes around any closed loop is zero (conservation of energy)."],
      ["Circuits: resistivity", "How does the resistance of a wire depend on its geometry?", "R = rho L / A; longer wires have more resistance, and thicker wires have less."],
      ["Circuits: capacitance", "What is the definition of capacitance?", "C = Q/V"],
      ["Circuits: parallel plate capacitor", "What is the capacitance of a parallel plate capacitor?", "C = kappa epsilon0 A / d; a dielectric (kappa) increases it."],
      ["Circuits: capacitors in parallel", "How do capacitors combine in parallel and in series?", "Parallel: C eq = C1 + C2. Series: 1/C eq = 1/C1 + 1/C2 (the opposite of resistors)."],
      ["Circuits: energy in a capacitor", "How much energy does a capacitor store?", "U = (1/2)CV^2 = (1/2)QV"],
      ["Circuits: ammeters and voltmeters", "How are ammeters and voltmeters connected?", "Ammeters in series (low resistance); voltmeters in parallel (high resistance)."],
      ["Circuits: internal resistance", "What is the terminal voltage of a battery with internal resistance?", "V terminal = emf - Ir"],
      ["Circuits: electric field", "What is the force on a charge in an electric field?", "F = qE; the direction is along E for positive charges."],
    ],
  },
  {
    name: "Light, Optics & Sound",
    description: "Reflection, refraction, lenses, mirrors, and wave behavior.",
    cards: [
      ["Waves: speed equation", "What is the relationship between wave speed, frequency, and wavelength?", "v = f lambda"],
      ["Waves: light speed", "What is the speed of light in a vacuum?", "c = 3.0 x 10^8 m/s."],
      ["Waves: photon energy", "How do you calculate the energy of a photon?", "E = hf = hc/lambda"],
      ["Optics: index of refraction", "What is the index of refraction?", "n = c/v; light slows down in a medium with higher n."],
      ["Optics: Snell's law", "What is Snell's law?", "n1 sin(theta1) = n2 sin(theta2)"],
      ["Optics: refraction direction", "When light enters a medium with a higher index, which way does it bend?", "Toward the normal."],
      ["Optics: total internal reflection", "When does total internal reflection occur?", "When light goes from higher n to lower n at an angle beyond the critical angle: sin(theta c) = n2/n1."],
      ["Optics: mirror equation", "What are the mirror/lens equation and magnification?", "1/f = 1/o + 1/i; M = -i/o."],
      ["Optics: focal length", "What is the focal length of a spherical mirror?", "f = r/2; positive for concave mirrors, negative for convex mirrors."],
      ["Optics: converging lens", "What image does a converging lens form when the object is beyond 2f?", "A real, inverted, reduced image between f and 2f."],
      ["Optics: diverging lens", "What image does a diverging lens or convex mirror always form?", "A virtual, upright, reduced image."],
      ["Optics: lens power", "How is lens power defined?", "P = 1/f in diopters (f in meters); lens powers add for lenses in contact."],
      ["Waves: diffraction", "What is the single-slit condition for destructive interference?", "a sin(theta) = m lambda, for m = 1, 2, 3, ...; the double-slit constructive condition is d sin(theta) = m lambda."],
      ["Sound: Doppler effect", "What happens to observed frequency when a source moves toward an observer?", "It increases (higher pitch); it decreases as the source moves away."],
      ["Sound: intensity", "How is the decibel level of sound defined?", "beta = 10 log(I/I0); every 10 dB is a factor of 10 in intensity."],
    ],
  },
  {
    name: "Substitution & Elimination (SN1, SN2, E1, E2)",
    description: "Mechanisms, substrate effects, and conditions for substitution and elimination.",
    cards: [
      ["SN2: mechanism", "What is the SN2 mechanism?", "A one-step, concerted backside attack by the nucleophile with inversion of configuration."],
      ["SN2: rate law", "What is the rate law for SN2?", "Rate = k[substrate][nucleophile] (second order)."],
      ["SN2: substrate preference", "Which substrates favor SN2?", "Methyl > primary > secondary; tertiary does not react because of steric hindrance."],
      ["SN2: solvents", "What type of solvent favors SN2?", "Polar aprotic solvents (DMSO, acetone, DMF), which leave the nucleophile unsolvated."],
      ["SN1: mechanism", "What is the SN1 mechanism?", "A two-step process: the leaving group departs to form a carbocation, then the nucleophile attacks."],
      ["SN1: rate law", "What is the rate law for SN1?", "Rate = k[substrate] (first order); the nucleophile is not involved in the rate-determining step."],
      ["SN1: stereochemistry", "What is the stereochemical outcome of SN1?", "Racemization (a mix of retention and inversion) because the carbocation is planar."],
      ["SN1: substrate preference", "Which substrates favor SN1?", "Tertiary > secondary (carbocation stability; allylic and benzylic also work)."],
      ["SN1: solvents", "What type of solvent favors SN1?", "Polar protic solvents (water, alcohols), which stabilize the carbocation and the leaving group."],
      ["Carbocations: rearrangement", "What can happen to a carbocation after it forms?", "Hydride or alkyl shifts to give a more stable carbocation."],
      ["Leaving groups", "What makes a good leaving group?", "A weak base that is stable on its own, e.g. I-, Br-, tosylate; OH- is poor unless protonated."],
      ["Nucleophiles: strength", "What factors affect nucleophilicity?", "Negative charge, lower electronegativity, and larger size (in protic solvents); less steric hindrance."],
      ["E2: mechanism", "What is the E2 mechanism?", "A one-step, concerted elimination with a strong base and anti-periplanar geometry; rate = k[substrate][base]."],
      ["E1: mechanism", "What is the E1 mechanism?", "A two-step elimination through a carbocation; competes with SN1, favored by heat."],
      ["Elimination: Zaitsev", "What is Zaitsev's rule?", "The more substituted (more stable) alkene is the major product, unless a bulky base is used (which gives the Hofmann product)."],
    ],
  },
  {
    name: "Carbonyl Chemistry",
    description: "Aldehydes, ketones, carboxylic acid derivatives, and enolates.",
    cards: [
      ["Carbonyl: reactivity", "Why is the carbonyl carbon electrophilic?", "The C=O bond is polarized toward oxygen, so carbon has a partial positive charge."],
      ["Carbonyl: nucleophilic addition", "What is the mechanism of nucleophilic addition to an aldehyde or ketone?", "The nucleophile attacks the carbonyl carbon, forming a tetrahedral alkoxide, which is then protonated."],
      ["Carbonyl: aldehyde vs ketone", "Which is more reactive toward nucleophiles, an aldehyde or a ketone?", "Aldehydes: less steric hindrance and less electron donation to the carbonyl carbon."],
      ["Carbonyl: hydrates", "What forms when an aldehyde reacts with water?", "A gem-diol (hydrate), in equilibrium."],
      ["Carbonyl: acetals", "How do you form an acetal, and what is it used for?", "An aldehyde or ketone reacts with two equivalents of alcohol under acid; used as a protecting group."],
      ["Carbonyl: imines", "What does an aldehyde or ketone give with a primary amine?", "An imine (Schiff base), with loss of water."],
      ["Carbonyl: Grignard", "What does a Grignard reagent do with an aldehyde or ketone?", "Adds to the carbonyl to give an alcohol: formaldehyde gives primary, other aldehydes secondary, ketones tertiary."],
      ["Carbonyl: reduction", "What do NaBH4 and LiAlH4 do?", "NaBH4 reduces aldehydes and ketones to alcohols; LiAlH4 is stronger and also reduces esters, acids, and amides."],
      ["Carbonyl: acid derivative reactivity", "What is the order of reactivity of carboxylic acid derivatives?", "Acid chloride > anhydride > ester > amide."],
      ["Carbonyl: nucleophilic acyl substitution", "What is the mechanism of nucleophilic acyl substitution?", "Addition to give a tetrahedral intermediate, then elimination of the leaving group (addition-elimination)."],
      ["Carbonyl: Fischer esterification", "How is an ester made from a carboxylic acid?", "Heat the acid with an alcohol and an acid catalyst (Fischer esterification); it is reversible."],
      ["Carbonyl: saponification", "What is saponification?", "Base hydrolysis of an ester to a carboxylate and an alcohol; essentially irreversible."],
      ["Carbonyl: alpha hydrogens", "Why are the alpha hydrogens of carbonyls acidic?", "Deprotonation gives a resonance-stabilized enolate; pKa is about 20 for ketones."],
      ["Carbonyl: aldol", "What is an aldol condensation?", "An enolate attacks another carbonyl to form a beta-hydroxy carbonyl, which can dehydrate to an alpha,beta-unsaturated carbonyl."],
      ["Carbonyl: keto-enol", "What is keto-enol tautomerism?", "An equilibrium between the carbonyl and enol forms through proton shifts; the keto form usually dominates."],
    ],
  },
  {
    name: "Spectroscopy & Separations",
    description: "IR, NMR, UV-vis, mass spec, and lab separation techniques.",
    cards: [
      ["IR: carbonyl stretch", "Where does a carbonyl (C=O) stretch appear in IR?", "A strong, sharp peak at about 1700 cm^-1."],
      ["IR: O-H stretch", "What does an alcohol O-H look like in IR, and a carboxylic acid O-H?", "Alcohol: broad, about 3200-3600 cm^-1. Carboxylic acid: very broad, about 2500-3300 cm^-1."],
      ["IR: N-H stretch", "What does an N-H stretch look like in IR?", "About 3300-3500 cm^-1; primary amines show two peaks, secondary show one."],
      ["IR: C-H stretches", "Where do sp3, sp2, and sp C-H stretches appear?", "Just below 3000 (sp3), just above 3000 (sp2), and about 3300 cm^-1 (sp, sharp)."],
      ["IR: fingerprint region", "What is the IR fingerprint region?", "Below about 1500 cm^-1; a complex pattern unique to each compound."],
      ["NMR: chemical shift", "What does chemical shift tell you?", "The electronic environment of a nucleus; electronegative groups deshield and move peaks downfield (higher ppm)."],
      ["NMR: aldehyde proton", "Where do aldehyde and carboxylic acid protons appear in 1H NMR?", "Aldehyde: about 9-10 ppm. Carboxylic acid: about 10-12 ppm."],
      ["NMR: aromatic protons", "Where do aromatic protons appear in 1H NMR?", "About 6.5-8 ppm."],
      ["NMR: splitting", "What is the n+1 rule?", "A proton with n neighboring protons on adjacent carbons is split into n+1 peaks."],
      ["NMR: integration", "What does integration tell you?", "The relative number of protons giving each signal."],
      ["NMR: 13C", "How is 13C NMR different from 1H NMR?", "Each unique carbon gives one peak (usually decoupled, no splitting); the C=O carbon appears at about 160-220 ppm."],
      ["UV-vis: conjugation", "How does conjugation affect UV-vis absorbance?", "More conjugation shifts absorption to longer wavelengths (lower energy)."],
      ["Mass spec: molecular ion", "What is the molecular ion peak in mass spec?", "The peak (M+) with m/z equal to the molecular mass of the compound."],
      ["Separations: extraction", "How does acid-base extraction separate compounds?", "Acids and bases are converted into water-soluble salts, moving them into the aqueous layer."],
      ["Separations: chromatography", "In normal-phase column or TLC, which compounds elute first?", "The less polar compounds, since the stationary phase (silica) is polar."],
    ],
  },
  {
    name: "Stereochemistry",
    description: "Chirality, R/S assignments, stereoisomers, and conformations.",
    cards: [
      ["Stereo: chiral center", "What is a chiral center?", "A carbon bonded to four different groups."],
      ["Stereo: enantiomers", "What are enantiomers?", "Non-superimposable mirror images; they have identical physical properties except for the rotation of plane-polarized light."],
      ["Stereo: diastereomers", "What are diastereomers?", "Stereoisomers that are not mirror images; they have different physical properties."],
      ["Stereo: CIP rules", "How do you assign R or S?", "Rank the groups by atomic number, point the lowest priority away, and trace 1 to 3: clockwise is R, counterclockwise is S."],
      ["Stereo: optical activity", "What does a (+) or (-) sign mean?", "The direction of plane-polarized light rotation (dextrorotatory/levorotatory); it is not related to R or S."],
      ["Stereo: racemic mixture", "What is a racemic mixture?", "An equal mix of two enantiomers; optically inactive."],
      ["Stereo: meso compounds", "What is a meso compound?", "A compound with chiral centers and an internal plane of symmetry, making it achiral and optically inactive."],
      ["Stereo: number of stereoisomers", "What is the maximum number of stereoisomers for n chiral centers?", "2^n."],
      ["Stereo: cis/trans and E/Z", "What do E and Z mean?", "Z: higher-priority groups on the same side of the double bond. E: opposite sides."],
      ["Stereo: epimers", "What are epimers?", "Diastereomers that differ at exactly one chiral center, e.g. glucose and galactose."],
      ["Stereo: Fischer projections", "How do you read a Fischer projection?", "Horizontal bonds point toward you, vertical bonds point away; swapping two groups inverts the configuration."],
      ["Stereo: cyclohexane", "Why is the chair the most stable cyclohexane conformation?", "It has no angle strain and staggered bonds, so there is no torsional strain."],
      ["Stereo: axial vs equatorial", "Where do bulky substituents prefer to sit on a chair?", "Equatorial, to avoid 1,3-diaxial interactions."],
      ["Stereo: Newman projections", "Which conformation of butane is the most stable and which is the least?", "Anti (staggered) is the most stable; fully eclipsed (methyls aligned) is the least."],
      ["Stereo: SN2 and chirality", "What is the stereochemical outcome of an SN2 reaction at a chiral center?", "Inversion of configuration (Walden inversion)."],
    ],
  },
];
